### ISSUE TITLE
DB locked error

### ISSUE THREAD

**Issue by kristapsbe** [kristapsbe/meteo_server#10]
[2024-11-12 17:00:19,197.197] ERROR [139906731345728] - Exception in ASGI application
Traceback (most recent call last):
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/main.py", line 482, in get_city_forecasts
    city = get_closest_city(cur=cur, lat=lat, lon=lon, force_all=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/main.py", line 113, in get_closest_city
    cities = cur.execute(f"""
             ^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

**Comment by kristapsbe** [comment]
Should add a flag to indicate that db is being updated, and requests should wait

**Comment by kristapsbe** [comment]
a cache is an option as well (or, maybe, 2 sqlite files?) - looks like I return no results for few seconds during the update

**Comment by kristapsbe** [comment]
should have a fix now
