### ISSUE TITLE
Getting occasional exceptions when retrieving aurora forecasts

### ISSUE THREAD

**Issue by kristapsbe** [kristapsbe/meteo_server#7]
[2024-10-04 14:20:13,463.463] ERROR [140313194768192] - Exception in ASGI application
Traceback (most recent call last):
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/.venv/lib64/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/main.py", line 296, in get_city_forecasts
    return get_city_reponse(city, lat, lon, add_params, add_aurora)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/main.py", line 288, in get_city_reponse
    ret_val["aurora_probs"] = get_aurora_probability(cur, lat, lon)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meteo_server/main.py", line 225, in get_aurora_probability
    aurora_probs = cur.execute(f"""
                   ^^^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by kristapsbe** [comment]
looks like it blows up around once a day (?) I suspect I'm not updating the db properly

**Comment by kristapsbe** [comment]
https://github.com/kristapsbe/meteo_server/commit/4cbef6556af648d0949cd48def4b5cf7c08deeda should resolve the issue
